backend:
  name: git-gateway
  branch: main # Atau master, sesuaikan dengan nama branch GitHub lo

media_folder: "images/uploads" # Tempat foto berita disimpan
public_folder: "/images/uploads"

collections:
  - name: "berita"
    label: "Berita & Rilisan"
    folder: "content/berita"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Judul Berita", name: "title", widget: "string" }
      - { label: "Tanggal Publish", name: "date", widget: "datetime" }
      - { label: "Foto Utama", name: "thumbnail", widget: "image" }
      - { label: "Isi Berita", name: "body", widget: "markdown" }