backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "berita"
    label: "Berita & Rilisan"
    folder: "content/berita"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Judul Berita", name: "title", widget: "string" }
      - { label: "Tanggal Publish", name: "date", widget: "datetime" }
      - {
          label: "Foto Utama",
          name: "thumbnail",
          widget: "image",
          required: false,
        }
      - {
          label: "Link Streaming / Lagu",
          name: "song_link",
          widget: "string",
          required: false,
        }
      - {
          label: "Upload File Audio",
          name: "audio_file",
          widget: "file",
          required: false,
        }
      - { label: "Isi Berita", name: "body", widget: "markdown" }
